# Generated by Django 3.2.6 on 2021-09-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artworkID', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderPrice', models.IntegerField()),
                ('orderDate', models.DateField(max_length=20)),
                ('artworkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.artwork')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
    ]
